# -*- coding: utf-8 -*-
"""AI_engineer_salaries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wu9z0pKCQ8WqjM8WVf3hToK0qXd6SdS1
"""

import matplotlib.pyplot as plt

# Data
positions = ["Entry-Level", "Mid-Level", "Senior"]
salaries = [118166, 147880, 163037]

# Create a bar chart
plt.figure(figsize=(8, 6))
plt.bar(positions, salaries, color=['blue', 'green', 'red'])
plt.xlabel("AI Engineer Experience Level")
plt.ylabel("Average Salary ($)")
plt.title("AI Engineer Salary by Experience Level")
plt.ylim(0, 220000)  # Set the y-axis range to match the highest salary value
plt.show()